apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-plav
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-plav
    app.kubernetes.io/part-of: tkwch-fix-0075-0032-app
  name: devfile-sample-plav
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-plav
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-plav
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0032-tenant/tkwch-fix-0075-0032-app/devfile-sample-plav@sha256:48d7f2168565d96f7fa4a1e8ad62ec93bfb31df5c17860eac9a12ed62ea530fe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
